spring.application.name=desafio-veiculos

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

# Liquibase Configuration
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

# AwesomeAPI Configuration
awesome.api.url=https://economia.awesomeapi.com.br/json/last/USD-BRL
frankfurter.api.url=https://api.frankfurter.app/latest?from=USD&to=BRL
